### PR TITLE
Add goodbye message

### PR DESCRIPTION
**Pull request by enitschorn**
This PR adds a goodbye message to round up the file.

### CODE REVIEW

**Comment by scallywag89** [comment]
Amazing! This looks good to me :D

**Review by enitschorn — COMMENTED** [review]
This is great.

**Comment by Chuxerador** [comment]
Yeah, looks great!

**Comment by mmadalenas** [comment]
I comment below, not in the add goodbye message link.

**Comment by vicky356** [comment]
Thanks for the lesson!

**Pull request merged**
